import { useEffect } from "react";

import type { Metadata } from "next";
import { Inter } from "next/font/google";

import { NextUiProvider } from "@/providers/nextui-provider";
import SessionProvider from "@/providers/session-provider";

import "./globals.css";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {


    
  return (
    <html lang="en">
      <body className={inter.className}>
        <NextUiProvider>
          <SessionProvider>
            {children}
          </SessionProvider>
        </NextUiProvider>
      </body>
    </html>
  );
}
